CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255)NOT NULL,
    login varchar(255)NOT NULL,
    name varchar(255),
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS statuses (
    statuses_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id int NOT NULL REFERENCES users(id),
    friend_id int NOT NULL REFERENCES users(id),
    statuses_id int REFERENCES statuses(statuses_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genres_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS MPA (
     mpa_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name varchar(255)
);

create table IF NOT EXISTS films (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name varchar(255) NOT NULL,
     description varchar(255)NOT NULL,
     release_date date NOT NULL,
     duration int NOT NULL,
     mpa_id int REFERENCES  MPA(mpa_id)
);

create table if not exists genres_film (
    film_id int REFERENCES films(id) NOT NULL ,
    genres_id int REFERENCES genres(genres_id) NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    like_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES users(id),
    film_id int REFERENCES films(id)
);